name: Code Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  code-check:
    name: Code Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Pylance code check
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -U pip
          pip install --pre 'pylance[pyright]'
          pylance --output json --config .pyrightconfig.json > code_check_result.json