name: Ruff Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ruff-check:
    name: Ruff Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install Ruff CLI
        run: npm install @ruff/cli
      
      - name: Run Ruff check
        run: npx ruff check