name: Test-python-dependencies
on:
  push:
    branches: [ main, dev-main ]
  pull_request:
    branches: [ main, dev-main ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9","3.10","3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install poetry
        poetry install --no-dev
    - name: Test with pytest
      run: |
        pytest