name: Test-python-dependencies
on:
  push:
    branches: [ 1.x.x ]
  pull_request:
    branches: [ 1.x.x ]
jobs:
  test:  # 更合适的 job 名称
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.12"]
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4  # 升级到 v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install PDM
      run: pip install pdm
    
    - name: Install project dependencies
      run: |
        pdm install -G test  # 假设 test 组包含测试依赖
        pdm add pytest pytest-asyncio  # 确保测试依赖存在
    
    - name: Run tests
      run: pdm run pytest -v  # 添加 -v 获取详细输出