name: Test-python-dependencies
on:
  push:
    branches: [ 1.x.x ]
  pull_request:
    branches: [ 1.x.x ]
jobs:
  test:
    if: github.repository == 'Agnes4m/nonebot_plugin_l4d2_server'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.12"]
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install PDM
      run: pip install pdm
    
    - name: Install project dependencies
      run: |
        pdm install -G test
        pdm add pytest pytest-asyncio uvicorn 
    
    - name: Run tests
      run: pdm run pytest -v